# Generated by Django 4.2.3 on 2023-10-11 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esupport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            
        ),
        migrations.CreateModel(
            name='Perifericos',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(
                    blank=True, null=True, upload_to='productos/')),
            ],
        ),
        migrations.CreateModel(
            name='ProveedoresProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='user',
        ),
        migrations.AddField(
            model_name='categoriaproducto',
            name='imagen',
            field=models.ImageField(
                blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(
                blank=True, null=True, upload_to='productos/'),
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('imagen', models.ImageField(
                    blank=True, null=True, upload_to='productos/')),
                ('productoproveedor', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.CASCADE, to='esupport.proveedoresproducto')),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=200, null=True)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('producto', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='esupport.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='esupport.marcaproducto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='perifericos',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='esupport.perifericos'),
        ),
    ]
