# Generated by Django 4.2.3 on 2023-07-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esupport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
