# Generated by Django 4.2.3 on 2023-07-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esupport', '0007_categoriaproducto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periféricos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
            ],
        ),
    ]
