# Generated by Django 4.2.3 on 2023-08-05 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esupport', '0012_proveedores'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedoresProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='esupport.proveedoresproducto'),
        ),
    ]
