# Generated by Django 4.2.3 on 2023-08-06 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esupport', '0013_proveedoresproducto_alter_proveedores_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedores',
            old_name='producto',
            new_name='productoproveedor',
        ),
    ]
